### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by sjw1230** [ebagdasa/federated_adaptation#3]
Excuse me，Sir.
The ERROR is
Traceback (most recent call last):
  File "training.py", line 157, in <module>
    runner_helper.load_data()
  File "E:\GoogleDownload\federated_adaptation-master\utils\text_helper.py", line 70, in load_data
    self.corpus.train]
  File "E:\GoogleDownload\federated_adaptation-master\utils\text_helper.py", line 69, in <listcomp>
    self.train_data = [self.batchify(data_chunk, self.batch_size) for data_chunk in
  File "E:\GoogleDownload\federated_adaptation-master\utils\text_helper.py", line 22, in batchify
    return data.cuda()
  File "E:\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 196, in _lazy_init
    _check_driver()
  File "E:\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 94, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

I have changed some methods but it doesn't work, I have no GPU, so I should run it with CPU, but it is not right.

**Comment by ebagdasa** [comment]
This code is for cuda, we don’t support anything else.
